workflows:

  react-native-android:

    name: React Native Android

    max_build_duration: 120

    instance_type: mac_mini_m2

    environment:
      # no publishing integrations required for a local APK build
      groups: []
      vars:
        # you can set PACKAGE_NAME if you need it elsewhere, not required for the APK build itself
        PACKAGE_NAME: "io.codemagic.sample.reactnative"

    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"

      - name: Install npm dependencies
        script: |
          npm install

      - name: Run Expo prebuild (android)
        script: |
          npx expo prebuild --platform android

      - name: Set up android/app/build.gradle
        script: |
          # copy the provided build.gradle into android/app (use copy so the original remains in the workspace)
          cp -f ./support-files/build.gradle android/app/build.gradle || true

      - name: Build Android release APK
        script: |
          # For simple testing builds we use the CI BUILD_NUMBER if available, fallback to 1
          UPDATED_BUILD_NUMBER=${BUILD_NUMBER:-1}

          cd android

          # build the release APK (assembleRelease produces APKs; bundleRelease produces an AAB)
          ./gradlew assembleRelease \
            -PversionCode=$UPDATED_BUILD_NUMBER \
            -PversionName=1.0.$UPDATED_BUILD_NUMBER

    artifacts:
      # release APKs (if signing config exists in your build.gradle, release APK will be signed)
      - android/app/build/outputs/**/*.apk
